[package]
name = "read_from_computer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
os_info="3.8.2"
sysinfo = "0.30.10"